// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://fdqgvjgcoidqwvemavaa.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkcWd2amdjb2lkcXd2ZW1hdmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzMjQwMTAsImV4cCI6MjA0ODkwMDAxMH0.-IuGTf07mMhtEQl9wtpTSG5PB5fNHS95f6PCEkJwUEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);